// Sample Questions and Learning Content for Different Topics
import { AssessmentQuestion, QuestionAndAnswer } from '../types';

// Learning Phase: Questions & Answers for Understanding
export const learningContent: Record<string, QuestionAndAnswer[]> = {
  'Renewable Energy Innovation': [
    {
      id: 'learn_re_1',
      topic: 'Renewable Energy Innovation',
      question: 'What is renewable energy?',
      answer: 'Renewable energy is energy derived from natural sources that are replenished at a higher rate than they are consumed. Examples include sunlight, wind, rain, tides, waves, and geothermal heat. Unlike fossil fuels, renewable energy sources produce little to no greenhouse gas emissions.',
      difficulty: 'easy',
      category: 'Fundamentals'
    },
    {
      id: 'learn_re_2',
      topic: 'Renewable Energy Innovation',
      question: 'What are the main types of renewable energy?',
      answer: 'The main types of renewable energy are: 1) Solar Energy - captured from sunlight using photovoltaic cells or solar thermal systems, 2) Wind Energy - generated by wind turbines, 3) Hydroelectric Power - produced from flowing water, 4) Geothermal Energy - heat from within the Earth, 5) Biomass Energy - from organic materials, and 6) Ocean Energy - from tides and waves.',
      difficulty: 'easy',
      category: 'Types'
    },
    {
      id: 'learn_re_3',
      topic: 'Renewable Energy Innovation',
      question: 'How do solar panels work?',
      answer: 'Solar panels work through the photovoltaic effect. When sunlight hits the solar cells, photons knock electrons loose from atoms, generating electricity. The solar cells are made of semiconductor materials (typically silicon) with positive and negative layers that create an electric field. This field drives the electrons through wires, creating electrical current.',
      difficulty: 'medium',
      category: 'Technology'
    },
    {
      id: 'learn_re_4',
      topic: 'Renewable Energy Innovation',
      question: 'What are the benefits of renewable energy?',
      answer: 'Benefits of renewable energy include: 1) Environmental - reduces greenhouse gas emissions and air pollution, 2) Sustainability - inexhaustible energy sources, 3) Economic - creates jobs and reduces energy costs in long term, 4) Energy Independence - reduces reliance on imported fossil fuels, 5) Grid Resilience - distributed generation increases reliability, and 6) Health Benefits - cleaner air reduces respiratory and cardiovascular diseases.',
      difficulty: 'medium',
      category: 'Benefits'
    },
    {
      id: 'learn_re_5',
      topic: 'Renewable Energy Innovation',
      question: 'What are the challenges in renewable energy adoption?',
      answer: 'Key challenges include: 1) Intermittency - solar and wind are weather-dependent, 2) Storage - battery technology needs improvement, 3) Initial Costs - high upfront investment, 4) Infrastructure - requires grid upgrades and new transmission lines, 5) Land Use - requires significant space, especially for solar farms and wind turbines, and 6) Geographic Limitations - not all regions have equal access to renewable resources.',
      difficulty: 'hard',
      category: 'Challenges'
    }
  ],
  'Artificial Intelligence': [
    {
      id: 'learn_ai_1',
      topic: 'Artificial Intelligence',
      question: 'What is Artificial Intelligence?',
      answer: 'Artificial Intelligence (AI) is the simulation of human intelligence processes by machines, especially computer systems. These processes include learning (acquiring information and rules), reasoning (using rules to reach conclusions), and self-correction. AI can be categorized into Narrow AI (designed for specific tasks) and General AI (theoretical human-level intelligence).',
      difficulty: 'easy',
      category: 'Fundamentals'
    },
    {
      id: 'learn_ai_2',
      topic: 'Artificial Intelligence',
      question: 'What is machine learning?',
      answer: 'Machine Learning is a subset of AI that enables systems to learn and improve from experience without being explicitly programmed. It uses algorithms to analyze data, learn patterns, and make decisions. The three main types are: 1) Supervised Learning - learns from labeled data, 2) Unsupervised Learning - finds patterns in unlabeled data, and 3) Reinforcement Learning - learns through trial and error with rewards.',
      difficulty: 'medium',
      category: 'Core Concepts'
    },
    {
      id: 'learn_ai_3',
      topic: 'Artificial Intelligence',
      question: 'How do neural networks work?',
      answer: 'Neural networks are computing systems inspired by biological neural networks. They consist of layers of interconnected nodes (neurons): input layer, hidden layers, and output layer. Each connection has a weight that adjusts during training. Data flows through the network, with each neuron applying an activation function to its weighted inputs. Through backpropagation, the network adjusts weights to minimize errors and improve predictions.',
      difficulty: 'hard',
      category: 'Technology'
    }
  ],
  'Climate Change': [
    {
      id: 'learn_cc_1',
      topic: 'Climate Change',
      question: 'What is climate change?',
      answer: 'Climate change refers to long-term shifts in global temperatures and weather patterns. While climate variations occur naturally, since the 1800s, human activities have been the main driver of climate change, primarily due to burning fossil fuels which releases greenhouse gases. These gases trap heat in the atmosphere, causing global warming and changing climate patterns worldwide.',
      difficulty: 'easy',
      category: 'Fundamentals'
    },
    {
      id: 'learn_cc_2',
      topic: 'Climate Change',
      question: 'What are greenhouse gases?',
      answer: 'Greenhouse gases (GHGs) are gases in Earth\'s atmosphere that trap heat. The main GHGs are: 1) Carbon Dioxide (CO2) - from burning fossil fuels, 2) Methane (CH4) - from agriculture and landfills, 3) Nitrous Oxide (N2O) - from fertilizers, and 4) Fluorinated gases - from industrial processes. These gases allow sunlight to enter the atmosphere but prevent some of the heat from escaping back into space.',
      difficulty: 'medium',
      category: 'Science'
    }
  ]
};

// Assessment Phase: Questions for Testing Understanding
export const assessmentQuestions: Record<string, AssessmentQuestion[]> = {
  'Climate Change': [
    {
      id: 'assess_cc_1',
      question: 'What is the primary cause of current climate change?',
      type: 'multiple-choice',
      topic: 'Climate Change',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Natural climate variations',
        'Volcanic eruptions',
        'Human activities burning fossil fuels',
        'Solar radiation changes'
      ],
      correctAnswer: 'Human activities burning fossil fuels',
      points: 10
    },
    {
      id: 'assess_cc_2',
      question: 'Explain what greenhouse gases are and how they contribute to global warming. Provide at least three examples of greenhouse gases.',
      type: 'descriptive',
      topic: 'Climate Change',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    },
    {
      id: 'assess_cc_3',
      question: 'Describe the main impacts of climate change on ecosystems and human societies.',
      type: 'descriptive',
      topic: 'Climate Change',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_cc_4',
      question: 'What are the most effective strategies for mitigating climate change?',
      type: 'short-answer',
      topic: 'Climate Change',
      difficulty: 'medium',
      expectedTimeSeconds: 90,
      correctAnswer: 'Reducing emissions, renewable energy, reforestation, sustainable practices',
      points: 15
    },
    {
      id: 'assess_cc_5',
      question: 'Analyze the role of international agreements like the Paris Agreement in addressing climate change.',
      type: 'descriptive',
      topic: 'Climate Change',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Artificial Intelligence': [
    {
      id: 'assess_ai_1',
      question: 'What is the difference between Narrow AI and General AI?',
      type: 'short-answer',
      topic: 'Artificial Intelligence',
      difficulty: 'easy',
      expectedTimeSeconds: 60,
      correctAnswer: 'Narrow AI is designed for specific tasks, while General AI would have human-level intelligence',
      points: 10
    },
    {
      id: 'assess_ai_2',
      question: 'Which type of machine learning uses labeled data for training?',
      type: 'multiple-choice',
      topic: 'Artificial Intelligence',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Supervised Learning',
        'Unsupervised Learning',
        'Reinforcement Learning',
        'Deep Learning'
      ],
      correctAnswer: 'Supervised Learning',
      points: 10
    },
    {
      id: 'assess_ai_3',
      question: 'Explain how neural networks learn and improve their performance. Include the concepts of layers, weights, and backpropagation.',
      type: 'descriptive',
      topic: 'Artificial Intelligence',
      difficulty: 'hard',
      expectedTimeSeconds: 200,
      points: 25
    },
    {
      id: 'assess_ai_4',
      question: 'What are the main ethical concerns surrounding artificial intelligence?',
      type: 'descriptive',
      topic: 'Artificial Intelligence',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    },
    {
      id: 'assess_ai_5',
      question: 'Describe three real-world applications of AI and their impact on society.',
      type: 'descriptive',
      topic: 'Artificial Intelligence',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    }
  ],
  'Space Exploration': [
    {
      id: 'assess_se_1',
      question: 'Which organization successfully landed the first humans on the Moon?',
      type: 'multiple-choice',
      topic: 'Space Exploration',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'NASA',
        'ESA',
        'Roscosmos',
        'SpaceX'
      ],
      correctAnswer: 'NASA',
      points: 10
    },
    {
      id: 'assess_se_2',
      question: 'Explain the main challenges of sending humans to Mars.',
      type: 'descriptive',
      topic: 'Space Exploration',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_se_3',
      question: 'What is the purpose of the International Space Station (ISS)?',
      type: 'short-answer',
      topic: 'Space Exploration',
      difficulty: 'easy',
      expectedTimeSeconds: 60,
      correctAnswer: 'Scientific research, international cooperation, testing space technologies',
      points: 10
    },
    {
      id: 'assess_se_4',
      question: 'Describe the technological advancements that have made space exploration more accessible.',
      type: 'descriptive',
      topic: 'Space Exploration',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    },
    {
      id: 'assess_se_5',
      question: 'Analyze the potential benefits and risks of colonizing other planets.',
      type: 'descriptive',
      topic: 'Space Exploration',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Renewable Energy': [
    {
      id: 'assess_re_1',
      question: 'Which of the following is NOT a type of renewable energy?',
      type: 'multiple-choice',
      topic: 'Renewable Energy',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Solar Energy',
        'Natural Gas',
        'Wind Energy',
        'Geothermal Energy'
      ],
      correctAnswer: 'Natural Gas',
      points: 10
    },
    {
      id: 'assess_re_2',
      question: 'Explain how solar panels generate electricity from sunlight.',
      type: 'descriptive',
      topic: 'Renewable Energy',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_re_3',
      question: 'List three major benefits of renewable energy for society.',
      type: 'descriptive',
      topic: 'Renewable Energy',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 15
    },
    {
      id: 'assess_re_4',
      question: 'What is the main challenge related to solar and wind energy availability?',
      type: 'short-answer',
      topic: 'Renewable Energy',
      difficulty: 'easy',
      expectedTimeSeconds: 45,
      correctAnswer: 'Intermittency',
      points: 10
    },
    {
      id: 'assess_re_5',
      question: 'Describe the challenges in renewable energy adoption and propose solutions.',
      type: 'descriptive',
      topic: 'Renewable Energy',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Cybersecurity': [
    {
      id: 'assess_cs_1',
      question: 'What is the primary purpose of encryption in cybersecurity?',
      type: 'multiple-choice',
      topic: 'Cybersecurity',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'To protect data by converting it into unreadable format',
        'To delete viruses',
        'To speed up internet connection',
        'To backup data'
      ],
      correctAnswer: 'To protect data by converting it into unreadable format',
      points: 10
    },
    {
      id: 'assess_cs_2',
      question: 'Explain the difference between malware, phishing, and ransomware attacks.',
      type: 'descriptive',
      topic: 'Cybersecurity',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_cs_3',
      question: 'What are the key principles of secure password creation?',
      type: 'short-answer',
      topic: 'Cybersecurity',
      difficulty: 'easy',
      expectedTimeSeconds: 60,
      correctAnswer: 'Length, complexity, uniqueness, regular changes',
      points: 10
    },
    {
      id: 'assess_cs_4',
      question: 'Describe the role of firewalls and antivirus software in protecting computer systems.',
      type: 'descriptive',
      topic: 'Cybersecurity',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    },
    {
      id: 'assess_cs_5',
      question: 'Analyze the challenges organizations face in maintaining cybersecurity and recommend best practices.',
      type: 'descriptive',
      topic: 'Cybersecurity',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Quantum Computing': [
    {
      id: 'assess_qc_1',
      question: 'What is a qubit in quantum computing?',
      type: 'multiple-choice',
      topic: 'Quantum Computing',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'A quantum bit that can be 0, 1, or both simultaneously',
        'A regular computer bit',
        'A type of quantum particle',
        'A quantum measurement tool'
      ],
      correctAnswer: 'A quantum bit that can be 0, 1, or both simultaneously',
      points: 10
    },
    {
      id: 'assess_qc_2',
      question: 'Explain the concept of quantum superposition and its importance in quantum computing.',
      type: 'descriptive',
      topic: 'Quantum Computing',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_qc_3',
      question: 'What is quantum entanglement?',
      type: 'short-answer',
      topic: 'Quantum Computing',
      difficulty: 'medium',
      expectedTimeSeconds: 90,
      correctAnswer: 'Connection between particles where measuring one affects the other instantly',
      points: 15
    },
    {
      id: 'assess_qc_4',
      question: 'Describe potential applications of quantum computing in cryptography and drug discovery.',
      type: 'descriptive',
      topic: 'Quantum Computing',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_qc_5',
      question: 'Analyze the main challenges preventing widespread adoption of quantum computers.',
      type: 'descriptive',
      topic: 'Quantum Computing',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Biotechnology': [
    {
      id: 'assess_bt_1',
      question: 'What is CRISPR-Cas9 primarily used for?',
      type: 'multiple-choice',
      topic: 'Biotechnology',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Gene editing',
        'Protein synthesis',
        'Cell division',
        'DNA replication'
      ],
      correctAnswer: 'Gene editing',
      points: 10
    },
    {
      id: 'assess_bt_2',
      question: 'Explain how biotechnology is used in developing new medical treatments.',
      type: 'descriptive',
      topic: 'Biotechnology',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_bt_3',
      question: 'What are genetically modified organisms (GMOs)?',
      type: 'short-answer',
      topic: 'Biotechnology',
      difficulty: 'easy',
      expectedTimeSeconds: 60,
      correctAnswer: 'Organisms whose genetic material has been altered using genetic engineering',
      points: 10
    },
    {
      id: 'assess_bt_4',
      question: 'Describe the applications of biotechnology in agriculture and food production.',
      type: 'descriptive',
      topic: 'Biotechnology',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    },
    {
      id: 'assess_bt_5',
      question: 'Analyze the ethical considerations surrounding gene editing and biotechnology research.',
      type: 'descriptive',
      topic: 'Biotechnology',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Ocean Conservation': [
    {
      id: 'assess_oc_1',
      question: 'What percentage of Earth\'s surface is covered by oceans?',
      type: 'multiple-choice',
      topic: 'Ocean Conservation',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'About 71%',
        'About 50%',
        'About 85%',
        'About 60%'
      ],
      correctAnswer: 'About 71%',
      points: 10
    },
    {
      id: 'assess_oc_2',
      question: 'Explain the main threats facing ocean ecosystems today.',
      type: 'descriptive',
      topic: 'Ocean Conservation',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_oc_3',
      question: 'What is ocean acidification and what causes it?',
      type: 'short-answer',
      topic: 'Ocean Conservation',
      difficulty: 'medium',
      expectedTimeSeconds: 90,
      correctAnswer: 'Decrease in ocean pH caused by absorption of excess CO2 from atmosphere',
      points: 15
    },
    {
      id: 'assess_oc_4',
      question: 'Describe the role of coral reefs in marine ecosystems and why their conservation is important.',
      type: 'descriptive',
      topic: 'Ocean Conservation',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    },
    {
      id: 'assess_oc_5',
      question: 'Analyze strategies for reducing plastic pollution in oceans and their effectiveness.',
      type: 'descriptive',
      topic: 'Ocean Conservation',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Smart Cities': [
    {
      id: 'assess_sc_1',
      question: 'What is the primary goal of a smart city?',
      type: 'multiple-choice',
      topic: 'Smart Cities',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Using technology to improve quality of life and efficiency',
        'Building taller buildings',
        'Increasing population density',
        'Reducing green spaces'
      ],
      correctAnswer: 'Using technology to improve quality of life and efficiency',
      points: 10
    },
    {
      id: 'assess_sc_2',
      question: 'Explain how IoT (Internet of Things) contributes to smart city infrastructure.',
      type: 'descriptive',
      topic: 'Smart Cities',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_sc_3',
      question: 'What are smart grids in the context of smart cities?',
      type: 'short-answer',
      topic: 'Smart Cities',
      difficulty: 'easy',
      expectedTimeSeconds: 60,
      correctAnswer: 'Intelligent electricity networks that optimize energy distribution and consumption',
      points: 10
    },
    {
      id: 'assess_sc_4',
      question: 'Describe how smart transportation systems can reduce traffic congestion and pollution.',
      type: 'descriptive',
      topic: 'Smart Cities',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    },
    {
      id: 'assess_sc_5',
      question: 'Analyze the challenges cities face in becoming "smart" and propose solutions.',
      type: 'descriptive',
      topic: 'Smart Cities',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Digital Privacy': [
    {
      id: 'assess_dp_1',
      question: 'What is end-to-end encryption?',
      type: 'multiple-choice',
      topic: 'Digital Privacy',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Encryption where only sender and recipient can read messages',
        'Encryption of email addresses',
        'Encryption of website URLs',
        'Encryption of user passwords'
      ],
      correctAnswer: 'Encryption where only sender and recipient can read messages',
      points: 10
    },
    {
      id: 'assess_dp_2',
      question: 'Explain how companies collect and use personal data online.',
      type: 'descriptive',
      topic: 'Digital Privacy',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_dp_3',
      question: 'What is GDPR and why is it important?',
      type: 'short-answer',
      topic: 'Digital Privacy',
      difficulty: 'medium',
      expectedTimeSeconds: 90,
      correctAnswer: 'General Data Protection Regulation - EU law protecting personal data and privacy',
      points: 15
    },
    {
      id: 'assess_dp_4',
      question: 'Describe the risks associated with sharing personal information on social media.',
      type: 'descriptive',
      topic: 'Digital Privacy',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    },
    {
      id: 'assess_dp_5',
      question: 'Analyze the balance between personalization and privacy in digital services.',
      type: 'descriptive',
      topic: 'Digital Privacy',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Sustainable Transportation': [
    {
      id: 'assess_st_1',
      question: 'Which of the following is considered the most sustainable form of urban transportation?',
      type: 'multiple-choice',
      topic: 'Sustainable Transportation',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Electric public transit and cycling',
        'Diesel buses',
        'Gasoline cars',
        'Motorcycles'
      ],
      correctAnswer: 'Electric public transit and cycling',
      points: 10
    },
    {
      id: 'assess_st_2',
      question: 'Explain how electric vehicles contribute to reducing carbon emissions.',
      type: 'descriptive',
      topic: 'Sustainable Transportation',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_st_3',
      question: 'What is the main advantage of hydrogen fuel cell vehicles?',
      type: 'short-answer',
      topic: 'Sustainable Transportation',
      difficulty: 'medium',
      expectedTimeSeconds: 90,
      correctAnswer: 'Zero emissions, only water vapor as byproduct, fast refueling',
      points: 15
    },
    {
      id: 'assess_st_4',
      question: 'Describe the benefits of bike-sharing programs in urban areas.',
      type: 'descriptive',
      topic: 'Sustainable Transportation',
      difficulty: 'easy',
      expectedTimeSeconds: 120,
      points: 15
    },
    {
      id: 'assess_st_5',
      question: 'Analyze the challenges and opportunities in transitioning to sustainable transportation systems.',
      type: 'descriptive',
      topic: 'Sustainable Transportation',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ]
};

// Get learning content for a topic
export const getLearningContent = (topic: string): QuestionAndAnswer[] => {
  return learningContent[topic] || [];
};

// Get assessment questions for a topic
export const getAssessmentQuestions = (topic: string): AssessmentQuestion[] => {
  return assessmentQuestions[topic] || [];
};
