// Sample Questions and Learning Content for Different Topics
import { AssessmentQuestion, QuestionAndAnswer } from '../types';

// Learning Phase: Questions & Answers for Understanding
export const learningContent: Record<string, QuestionAndAnswer[]> = {
  'Renewable Energy Innovation': [
    {
      id: 'learn_re_1',
      topic: 'Renewable Energy Innovation',
      question: 'What is renewable energy?',
      answer: 'Renewable energy is energy derived from natural sources that are replenished at a higher rate than they are consumed. Examples include sunlight, wind, rain, tides, waves, and geothermal heat. Unlike fossil fuels, renewable energy sources produce little to no greenhouse gas emissions.',
      difficulty: 'easy',
      category: 'Fundamentals'
    },
    {
      id: 'learn_re_2',
      topic: 'Renewable Energy Innovation',
      question: 'What are the main types of renewable energy?',
      answer: 'The main types of renewable energy are: 1) Solar Energy - captured from sunlight using photovoltaic cells or solar thermal systems, 2) Wind Energy - generated by wind turbines, 3) Hydroelectric Power - produced from flowing water, 4) Geothermal Energy - heat from within the Earth, 5) Biomass Energy - from organic materials, and 6) Ocean Energy - from tides and waves.',
      difficulty: 'easy',
      category: 'Types'
    },
    {
      id: 'learn_re_3',
      topic: 'Renewable Energy Innovation',
      question: 'How do solar panels work?',
      answer: 'Solar panels work through the photovoltaic effect. When sunlight hits the solar cells, photons knock electrons loose from atoms, generating electricity. The solar cells are made of semiconductor materials (typically silicon) with positive and negative layers that create an electric field. This field drives the electrons through wires, creating electrical current.',
      difficulty: 'medium',
      category: 'Technology'
    },
    {
      id: 'learn_re_4',
      topic: 'Renewable Energy Innovation',
      question: 'What are the benefits of renewable energy?',
      answer: 'Benefits of renewable energy include: 1) Environmental - reduces greenhouse gas emissions and air pollution, 2) Sustainability - inexhaustible energy sources, 3) Economic - creates jobs and reduces energy costs in long term, 4) Energy Independence - reduces reliance on imported fossil fuels, 5) Grid Resilience - distributed generation increases reliability, and 6) Health Benefits - cleaner air reduces respiratory and cardiovascular diseases.',
      difficulty: 'medium',
      category: 'Benefits'
    },
    {
      id: 'learn_re_5',
      topic: 'Renewable Energy Innovation',
      question: 'What are the challenges in renewable energy adoption?',
      answer: 'Key challenges include: 1) Intermittency - solar and wind are weather-dependent, 2) Storage - battery technology needs improvement, 3) Initial Costs - high upfront investment, 4) Infrastructure - requires grid upgrades and new transmission lines, 5) Land Use - requires significant space, especially for solar farms and wind turbines, and 6) Geographic Limitations - not all regions have equal access to renewable resources.',
      difficulty: 'hard',
      category: 'Challenges'
    }
  ],
  'Artificial Intelligence': [
    {
      id: 'learn_ai_1',
      topic: 'Artificial Intelligence',
      question: 'What is Artificial Intelligence?',
      answer: 'Artificial Intelligence (AI) is the simulation of human intelligence processes by machines, especially computer systems. These processes include learning (acquiring information and rules), reasoning (using rules to reach conclusions), and self-correction. AI can be categorized into Narrow AI (designed for specific tasks) and General AI (theoretical human-level intelligence).',
      difficulty: 'easy',
      category: 'Fundamentals'
    },
    {
      id: 'learn_ai_2',
      topic: 'Artificial Intelligence',
      question: 'What is machine learning?',
      answer: 'Machine Learning is a subset of AI that enables systems to learn and improve from experience without being explicitly programmed. It uses algorithms to analyze data, learn patterns, and make decisions. The three main types are: 1) Supervised Learning - learns from labeled data, 2) Unsupervised Learning - finds patterns in unlabeled data, and 3) Reinforcement Learning - learns through trial and error with rewards.',
      difficulty: 'medium',
      category: 'Core Concepts'
    },
    {
      id: 'learn_ai_3',
      topic: 'Artificial Intelligence',
      question: 'How do neural networks work?',
      answer: 'Neural networks are computing systems inspired by biological neural networks. They consist of layers of interconnected nodes (neurons): input layer, hidden layers, and output layer. Each connection has a weight that adjusts during training. Data flows through the network, with each neuron applying an activation function to its weighted inputs. Through backpropagation, the network adjusts weights to minimize errors and improve predictions.',
      difficulty: 'hard',
      category: 'Technology'
    }
  ],
  'Climate Change': [
    {
      id: 'learn_cc_1',
      topic: 'Climate Change',
      question: 'What is climate change?',
      answer: 'Climate change refers to long-term shifts in global temperatures and weather patterns. While climate variations occur naturally, since the 1800s, human activities have been the main driver of climate change, primarily due to burning fossil fuels which releases greenhouse gases. These gases trap heat in the atmosphere, causing global warming and changing climate patterns worldwide.',
      difficulty: 'easy',
      category: 'Fundamentals'
    },
    {
      id: 'learn_cc_2',
      topic: 'Climate Change',
      question: 'What are greenhouse gases?',
      answer: 'Greenhouse gases (GHGs) are gases in Earth\'s atmosphere that trap heat. The main GHGs are: 1) Carbon Dioxide (CO2) - from burning fossil fuels, 2) Methane (CH4) - from agriculture and landfills, 3) Nitrous Oxide (N2O) - from fertilizers, and 4) Fluorinated gases - from industrial processes. These gases allow sunlight to enter the atmosphere but prevent some of the heat from escaping back into space.',
      difficulty: 'medium',
      category: 'Science'
    }
  ]
};

// Assessment Phase: Questions for Testing Understanding
export const assessmentQuestions: Record<string, AssessmentQuestion[]> = {
  'Renewable Energy Innovation': [
    {
      id: 'assess_re_1',
      question: 'Which of the following is NOT a type of renewable energy?',
      type: 'multiple-choice',
      topic: 'Renewable Energy Innovation',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Solar Energy',
        'Natural Gas',
        'Wind Energy',
        'Geothermal Energy'
      ],
      correctAnswer: 'Natural Gas',
      points: 10
    },
    {
      id: 'assess_re_2',
      question: 'Explain how solar panels generate electricity from sunlight. Include the role of photons, electrons, and semiconductor materials in your answer.',
      type: 'descriptive',
      topic: 'Renewable Energy Innovation',
      difficulty: 'medium',
      expectedTimeSeconds: 180,
      points: 20
    },
    {
      id: 'assess_re_3',
      question: 'List three major benefits of renewable energy and explain why each is important for society.',
      type: 'descriptive',
      topic: 'Renewable Energy Innovation',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 15
    },
    {
      id: 'assess_re_4',
      question: 'What is the main challenge related to solar and wind energy availability?',
      type: 'short-answer',
      topic: 'Renewable Energy Innovation',
      difficulty: 'easy',
      expectedTimeSeconds: 45,
      correctAnswer: 'Intermittency',
      points: 10
    },
    {
      id: 'assess_re_5',
      question: 'Describe the challenges in renewable energy adoption and propose solutions for at least two of these challenges.',
      type: 'descriptive',
      topic: 'Renewable Energy Innovation',
      difficulty: 'hard',
      expectedTimeSeconds: 240,
      points: 25
    }
  ],
  'Artificial Intelligence': [
    {
      id: 'assess_ai_1',
      question: 'What is the difference between Narrow AI and General AI?',
      type: 'short-answer',
      topic: 'Artificial Intelligence',
      difficulty: 'easy',
      expectedTimeSeconds: 60,
      correctAnswer: 'Narrow AI is designed for specific tasks, while General AI would have human-level intelligence',
      points: 10
    },
    {
      id: 'assess_ai_2',
      question: 'Which type of machine learning uses labeled data for training?',
      type: 'multiple-choice',
      topic: 'Artificial Intelligence',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Supervised Learning',
        'Unsupervised Learning',
        'Reinforcement Learning',
        'Deep Learning'
      ],
      correctAnswer: 'Supervised Learning',
      points: 10
    },
    {
      id: 'assess_ai_3',
      question: 'Explain how neural networks learn and improve their performance. Include the concepts of layers, weights, and backpropagation.',
      type: 'descriptive',
      topic: 'Artificial Intelligence',
      difficulty: 'hard',
      expectedTimeSeconds: 200,
      points: 25
    }
  ],
  'Climate Change': [
    {
      id: 'assess_cc_1',
      question: 'What is the primary cause of current climate change?',
      type: 'multiple-choice',
      topic: 'Climate Change',
      difficulty: 'easy',
      expectedTimeSeconds: 30,
      options: [
        'Natural climate variations',
        'Volcanic eruptions',
        'Human activities burning fossil fuels',
        'Solar radiation changes'
      ],
      correctAnswer: 'Human activities burning fossil fuels',
      points: 10
    },
    {
      id: 'assess_cc_2',
      question: 'Explain what greenhouse gases are and how they contribute to global warming. Provide at least three examples of greenhouse gases.',
      type: 'descriptive',
      topic: 'Climate Change',
      difficulty: 'medium',
      expectedTimeSeconds: 150,
      points: 20
    }
  ]
};

// Get learning content for a topic
export const getLearningContent = (topic: string): QuestionAndAnswer[] => {
  return learningContent[topic] || [];
};

// Get assessment questions for a topic
export const getAssessmentQuestions = (topic: string): AssessmentQuestion[] => {
  return assessmentQuestions[topic] || [];
};
